apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  project: default
  source:
    repoURL: https://github.com/privhlab/k8s-helm-charts.git
    path: csi
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true