apiVersion: v2
name: argocd
description: A Helm chart for argocd
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: argo-cd
  version: 7.8.14
  repository: "https://argoproj.github.io/argo-helm"