apiVersion: v2
name: metallb
description: A Helm chart for metallb
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: metallb
  version: 0.14.9
  repository: "https://metallb.github.io/metallb"