apiVersion: v2
name: minio
description: A Helm chart for minio
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: minio
  version: 16.0.10
  repository: "https://charts.bitnami.com/bitnami"